export const CART_ITEMS = "CART_ITEMS";
export const SHOULD_SHOW_CART = "SHOULD_SHOW_CART";

export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const SELECTED_PRODUCT_DETAILS = "SELECTED_PRODUCT_DETAILS";

export const IS_LOADING = "IS_LOADING";
